### ISSUE TITLE
Distinguish Events that are sent on custom server side.

### ISSUE THREAD

**Issue by dennym** [lucaspoffo/renet#37]
Heyhey. Currently I try to use renet on my bevy project to communicate with a simple elixir UDP server that just logs into the console while running.

~~As the the messages are send in bincode I already implemented some simple logic to get the bincode deserialized to an elixir struct.
Unfortunately my actual test text message I try to send is overshadowed by plenty of messages I believe come from the RenetClient.~~

This is I believe the Message that is internally sent by RenetClient. And I tried to get the binary back to a term. Unfortunately a simple  `:erlang.binary_to_term` won't work since the binary seems some different structure.
Maybe you have an idea or recommendation how I can implement this on elixir side. Maybe this is even worth a separate library to enable a different server language for renet.

best regards
Denny

**Comment by lucaspoffo** [comment]
Hey Denny,

If you are trying to read raw UDP packets on the Elixir side, this will be a hard endeavor,
since you need to implement the authentication and encryption protocol, which is done by [renetcode](https://github.com/lucaspoffo/renet/tree/master/renetcode). After that,
you would need to implement the protocol for reliable messages over UDP that is done in
[rechannel](https://github.com/lucaspoffo/renet/tree/master/rechannel).

My suggestion would be to use FFI bindings with renet on the elixir side. Some library like [rustler](https://github.com/rusterlium/rustler) could help I guess. I would check with someone in the elixir community about using Rust FFI and Elixir, maybe they know some better way to do what you want.

**Comment by dennym** [comment]
Ahh you caught me right in my edit :) I removed the whole `bincode` part since it is totally unimportant for the actual issue. It slowly dawned on me that I basically have to translate the server and the netcode to elixir to get anywhere. 

I already had the FFI in the back of my head. My experience in the past it is usually not that nice to use when the rust logic and return values are more complex. Its nice when there are 2 simple inputs and the return is a simple basic data type. But returning structs and enums through it becomes heavy. Usually while trying this the back of the head tries to negotiate with itself  to just write the whole thing by hand.

I will give it a go over the weekend and will come back with the results :)

Thanks for the input

**Comment by lucaspoffo** [comment]
I guess it would be still easier to use FFI instead of implementing the whole protocol. The only structs/enums are ServerEven, NetworkInfo, and Bytes I think, the others used types are basic ones. I've never done FFI so I'm not really how hard/possible it's :/

Anyway, good luck. I'll be closing this issue, but you can open a discussion (just enabled it on the repo) or post on this issue about your progress :)
