### ISSUE TITLE
Return `Vec<Payload>` wrapper on block channel to avoid memory copy?

### ISSUE THREAD

**Issue by minghuaw** [lucaspoffo/renet#49]
Most serde implementations provide a method (eg. `serde_json::from_reader(_)`) to deserialize any type that implements the `std::io::Read` trait. The block channel could probably return a thin wrapper over `Vec<Payload>` that both implements `std::io::Read` trait and provides access to the wrapped `Vec`? This would avoid unnecessary memory copy and, if the user want, the user could still use `copy_from_slice` to concatenate the payloads.

I have implemented this in my crate `fe2o3-amqp` and saw a 30% decrease in total time in an "unscientific" large content test (a couple of 10MB messages, the total time dropped from ~1.2 secs to ~0.8 secs). I can make a PR if this sounds like a good idea to you :)

**Comment by lucaspoffo** [comment]
I'm not sure if I understand the impl you are suggesting. Not sure how you would do a wrapper, since the Block channel slices the message in multiple chunks and serializes it in different packets and we need to reconstruct it in the client. Also, each payload in the Vec<Payload> is a different message, a wrapper over it would not be what you want.

But there could be places that could have better serialization with `serde`, not a specialist of it, especially with the Packets (de)serialization

**Comment by minghuaw** [comment]
I guess I didn't really understand the Block channel then. I thought that channel was meant to large content, where a single large message is split across many frames. I remember there was some memory copy when receiving partial transfers (it's been some time since I last look at it). Ignore me if I got it wrong
