### ISSUE TITLE
Possible race condition in the client/server test

### ISSUE THREAD

**Issue by paul-english** [lucaspoffo/renet#54]
Copying the `sending_and_receiving` test to my project I see it failing most of the time. When I clone the repo, I can see an occasional failure if I just continue to run & run the tests. Is there any insight into what might help in debugging this or stepping through where there might be a race condition or system thing occurring that could lead to this?

<img width="969" alt="Screen_Shot_2022-11-06_at_2 56 40_PM" src="https://user-images.githubusercontent.com/35297/201373795-b086e3b4-34e0-4120-885a-14aed57c8c9c.png">

**Comment by lucaspoffo** [comment]
I managed to reproduce once every ~20 tries. Seems to be that with 3 `app.update()`  establishing a connection may fail since we don't control the system order for the server/client update. Updating a few more times seems to fix it: d5f71f15651f9be28130ec15696266a976ef921c.

Can you check to see if it is fixed? I also added some trace logging to check the steps of the connection.

**Comment by Shatur** [comment]
But in your commit you updating it exactly 3 times. Maybe you wanted to write `0..4`?

**Comment by Shatur** [comment]
Maybe just wait for the connection by checking the client resource?
If the test is fuzzy, using the exact number of updates doesn't look good...

**Comment by lucaspoffo** [comment]
Made the client loop until it's connected: b9d2e637c7b37daea62b3b9434ba39ca5862bb57
