### ISSUE TITLE
Client disconnection design improvements

### ISSUE THREAD

**Issue by 50U10FCA7** [lucaspoffo/renet#59]
Hi! Some parts of `renet` library design is not clear for me.

#### Problem:

While trying to implement client-side disconnection handling, found that [`Client::disconnected`](https://github.com/lucaspoffo/renet/blob/f0602998c0542c3c344f88c8e08a6ee194cc8cd5/renet/src/client.rs#L114) returns type that [can't be accessed](https://github.com/lucaspoffo/renet/blob/f0602998c0542c3c344f88c8e08a6ee194cc8cd5/renet/src/lib.rs#LL4).

In my case I trying to implement 

```rust
impl From<renet::error::DisconnectionReason> for MyType { .. } // err

// some code

let Some(reason) = client.disconnected() else { .. };
return reason.into();

```

#### Possible fixes:

- make `error` module `pub` ([`rechannel`](https://github.com/lucaspoffo/renet/blob/f0602998c0542c3c344f88c8e08a6ee194cc8cd5/rechannel/src/lib.rs#L2) way).
- re-export `error::DisconnectionReason` instead of `rechannel:: DisconnectionReason` (which is already can be accessed) ([`renetcode`](https://github.com/lucaspoffo/renet/blob/f0602998c0542c3c344f88c8e08a6ee194cc8cd5/renetcode/src/lib.rs#LL28) way).

#### Problem:

It's unclear for me how client reconnection works. [`Client::disconnect`](https://github.com/lucaspoffo/renet/blob/f0602998c0542c3c344f88c8e08a6ee194cc8cd5/renet/src/client.rs#L127) makes `Client` [useless](https://github.com/lucaspoffo/renet/blob/f0602998c0542c3c344f88c8e08a6ee194cc8cd5/renet/src/client.rs#L180) after disconnection, because there is no way to reconnect it again (and as I see there is [no auto-reconnect](https://github.com/lucaspoffo/renet/blob/f0602998c0542c3c344f88c8e08a6ee194cc8cd5/renet/src/client.rs#L166) when new messages sent).

#### Possible fixes:

- Use `self` instead of `&mut self` in [`Client::disconnect`](https://github.com/lucaspoffo/renet/blob/f0602998c0542c3c344f88c8e08a6ee194cc8cd5/renet/src/client.rs#L127) to make `Client` [RAII](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization)-idiomatic.
- Provide `Client::connect` method to make `Client` instance reusable.

**Comment by lucaspoffo** [comment]
The missing public structs is an easy fix, I guess since I forgot to put the inner enum types as `pub` it still works :/

For the reconnection problem, I'm more inclined to make it reusable. Having an easy-to-use reconnect is important.
Currently, you need to recreate the client to reconnect. This is not the best solution and is also not documented.

**Comment by lucaspoffo** [comment]
After some thinking, I think not having a reconnect seems fine. As @UkoeHB said this keeps the API clear, and we need to keep track of less things. 

For the  `Use self instead of &mut self in Client::disconnectto make Client RAII, I feel it would be worse for the API, since there are multiple ways for a client to disconnect. We might want to keep the client - even if disconnected - to handle it at the same place as the others disconnections (ex: end of loop)

**Comment by lucaspoffo** [comment]
Note that the `DisconnectionReason` visibility problem is already fixed
